<!-- Updated: 2025-08-30T20:54:01.813Z -->
import './globals.css';
import type { Metadata } from 'next';
import DarkStreetsButton from '../components/DarkStreetsButton';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
        <meta name="theme-color" content="#000000" />
      </head>
      <body>
        {/* Header removed - banner now handled in page.tsx */}
        {children}
      </body>
    </html>
  );
}
