import { NextRequest, NextResponse } from 'next/server';
import { syncProductsFromShopify, getProductByVariantId } from '@/lib/shopify-product-sync';

/**
 * API endpoint to sync products from Shopify
 * GET /api/shopify/sync-products - Sync all products
 * GET /api/shopify/sync-products?variantId=123 - Get specific product
 */
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const variantId = searchParams.get('variantId');

    if (variantId) {
      // Get specific product by variant ID
      const product = await getProductByVariantId(parseInt(variantId));
      
      if (!product) {
        return NextResponse.json(
          { success: false, error: `Product not found for variant ID: ${variantId}` },
          { status: 404 }
        );
      }

      return NextResponse.json({
        success: true,
        product,
        message: `Product found for variant ${variantId}`
      });
    }

    // Sync all products
    const products = await syncProductsFromShopify();

    return NextResponse.json({
      success: true,
      products,
      count: products.length,
      message: `Successfully synced ${products.length} products from Shopify`
    });

  } catch (error) {
    console.error('Shopify sync API error:', error);
    
    return NextResponse.json(
      {
        success: false,
        error: 'Failed to sync products from Shopify',
        details: error instanceof Error ? error.message : String(error)
      },
      { status: 500 }
    );
  }
}

/**
 * API endpoint to update DS LLC products with Shopify data
 * POST /api/shopify/sync-products - Update products.ts with Shopify data
 */
export async function POST(request: NextRequest) {
  try {
    console.log('🔄 Starting product sync update...');
    
    const products = await syncProductsFromShopify();
    
    // Generate updated products.ts content
    const productsTsContent = generateProductsTsContent(products);
    
    return NextResponse.json({
      success: true,
      products,
      count: products.length,
      productsTsContent,
      message: `Generated updated products.ts with ${products.length} products`
    });

  } catch (error) {
    console.error('Shopify sync update error:', error);
    
    return NextResponse.json(
      {
        success: false,
        error: 'Failed to update products from Shopify',
        details: error instanceof Error ? error.message : String(error)
      },
      { status: 500 }
    );
  }
}

/**
 * Generate TypeScript content for products.ts file
 */
function generateProductsTsContent(products: any[]): string {
  const timestamp = new Date().toISOString();
  
  return `/**
 * Product Data - Synced from Shopify
 * Last updated: ${timestamp}
 * 
 * This file is automatically generated from Shopify Admin API.
 * Do not edit manually - changes will be overwritten.
 */

export interface Product {
  id: string;
  category: string;
  title: string;
  author: string;
  price: number;
  description: string;
  longDescription?: string;
  image: string;
  inStock: boolean;
  badge?: string;
  shopifyVariantId?: number;
  printfulVariantId?: string;
  requiresShipping?: boolean;
  sizeGuide?: {
    imperial: { [key: string]: { length: string; width: string } };
    metric: { [key: string]: { length: string; width: string } };
  };
  sizeGuideImages?: {
    imperial: string;
    metric: string;
    selector: string;
  };
}

export const products: Product[] = ${JSON.stringify(products, null, 2)};
`;
}
